### ISSUE TITLE
sql?

### ISSUE THREAD

**Issue by souzx17** [Setiawan007/STREAMNIME#3]
di mana saya bisa mendapatkan .sql ini

**Comment by nurhusni85** [comment]
devnya haho

**Comment by Setiawan007** [comment]
DM saya..

**Comment by nurhusni85** [comment]
Sql nya sebelah mana bang?

Pada tanggal Jum, 14 Jul 2023 08.20, Febrianto Bagus Setiawan <
***@***.***> menulis:
